# /*
#  * 245150200111028 Aditya Akbar
#  * 245150207111038 Mohammad Geisar Rampan
#  * 245150207111103 Muhammad Sulthon Aulia Wijaya
#  * 245150207111050 Orie Abyan Maulana
#  * 235150201111068 Pieter Christy Yan Yudhistira
#  */
ARG AIRFLOW_IMAGE_NAME=apache/airflow:3.0.0

FROM ${AIRFLOW_IMAGE_NAME}

COPY requirements.txt /requirements.txt

RUN pip install --no-cache-dir -r /requirements.txt